version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: acali_db
    restart: always
    environment:
      - POSTGRES_USER=acaliboss
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=acalidb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: